name: 'My Workflow'

on:
  push:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: 'Deploy to Netlify'
    steps:
      - uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          NETLIFY_AUTH_TOKEN: nfp_PfFVFfh8ZWqy3rnWm89mmARNZTjTRpKs7599
          NETLIFY_DEPLOY_TO_PROD: true
