name: 'My Workflow'

on:
  push:
     branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: 'Deploy to Netlify'
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: yarn install and build
        run: |
         npm install
         npm build
      - uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          NETLIFY_AUTH_TOKEN: nfp_PfFVFfh8ZWqy3rnWm89mmARNZTjTRpKs7599
          NETLIFY_DEPLOY_TO_PROD: true
